<a href="https://colab.research.google.com/github/karkichtn/DATA-SCIENCE/blob/main/Lect_6(manipulation_in_data_using_panda).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [94]:

import pandas as pd

dict = {
    'name':['Tom','NIck','Krish','Jack'],
    'age':[20,21,19,18],
    'roll':[1,2,3,4]
}


#dataframe
#complete structure of the data


df = pd.DataFrame(dict, index = ['a','b','c','d'])

df1 = pd.DataFrame(dict)

display(df)

display(df1)

#display

    name  age  roll
a    Tom   20     1
b   NIck   21     2
c  Krish   19     3
d   Jack   18     4

    name  age  roll
0    Tom   20     1
1   NIck   21     2
2  Krish   19     3
3   Jack   18     4

In [ ]:
df = pd.read_csv('student_data.csv')

# df.head(3)            #print first n rows by default it print first 5 rows


# df.tail()              # print last n rows by default it print last 5 rows


# df.shape




# df.info()               #give data about data also knowns as meta data(data ka data)
# print(" ")
# print(" ")


# df .describe()            #give more detail info about file or ddata


# df.columns                    #heading ke naam






# df.index                       #number of rows

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

RangeIndex(start=0, stop=10000, step=1)

In [ ]:
df = pd.read_csv('student_data.csv')


# df[['study_hours','internet_usage']]              #give columns of that particular name or heading
# df.study_hours                                      #give same but not recommended






# df.iloc[0: 5]                           #gives row of given parameter last range is not included



# df.loc[df['study_hours'] == 11 ]                  #gives study hours of those who have 11




# df.loc[df['study_hours'] == 11 ,  ['study_hours', 'sleep_hours']]                #bas study hours or sleep hours ki row ko print karega with condition study hours ==11



# df.loc[df['study_hours'] == 11 ,  ['study_hours', 'sleep_hours']].iloc[4: 8]          # 4 se 8 index ko hi print karega jiska study hours 11 hoga





#iloc works on index only                loc works on labels which meains work on conditions

df2= df.loc[df['study_hours']==11]


df2.loc[4]                       #loc proper label mein kaam karega mtlb ki agar index mein a or b likha hain toh tere ko paramenter mein a or b hi likh na parega par asliyat mein woh 0 or 1 index honge


df2.iloc[4: 8]                   #iloc mein index mein kaam karega mtlb tere ko 0 ya 1 hi daalna parega parameter mein agar file mein indexing a or b se hi kyu na ki ho

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
30,11,45,5,2,4,93,100.0,Placed
91,11,100,9,4,6,43,100.0,Placed
98,11,100,6,9,2,74,100.0,Placed
116,11,55,7,5,11,75,100.0,Placed

In [ ]:
#Question we have to print the 2nd row of the data where assignment ==8




df = pd.read_csv('student_data.csv')


df2=df.loc[df['assignments_completed']==8]



df2.iloc[1]

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

In [ ]:
#conditions

df= pd.read_csv('student_data.csv')


df[df["assignments_completed"]>3]               #loc mein column print hota tha mtlb loc mein parameter use kar sakte te isme nahi ,ye mtlb bas condition check kar ke puri table print karega, jo ki loc bhi kar sakta hain agar usme parameter na de toh







#add new column with name age with all value 20
df["age"] = 20
df





#rename columns

df.rename(columns = {'assignments_completed': 'assign_completed'}, inplace =True)        #inplace true hoga toh ussi file mein changes honge false hua toh new file banegi

df

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

In [100]:
df= pd.read_csv('student_data.csv')




#remove rows or columns

df.drop('study_hours', axis=1,inplace=True)
df


#remove missing values
data = {
    'name':['Tom','NIck','Krish','Jack'],
    'age':[20,21,19,None],
    'roll':[1,2,3,4]
}
df=pd.DataFrame(data)
df.dropna(inplace= True)
df



# #sort values by column
# df.sort_values()


# #sort index
# df.sort_index()


#check for missing values

    name   age  roll
0    Tom  20.0     1
1   NIck  21.0     2
2  Krish  19.0     3

In [108]:
#unique

df= pd.read_csv('student_data.csv')
df

#print the unique value in array
df['sleep_hours'].unique()

array([8, 5, 7, 9, 4, 6])