<a href="https://colab.research.google.com/github/karkichtn/DATA-SCIENCE/blob/main/Lecture_8(Merge%2C_pivot_table).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df1 = pd.DataFrame({
    'id':[1,2,3,4],
    'name':['Raju','Rani','Rahul','Rhea'],
    'age':[25,30,35,40]
})

df2 = pd.DataFrame({
    'id':[3,4,5,6],
    'name':['Rahul','Rhea','Ravi','Reena'],
    'age':[35,40,45,50]

})


df3 = pd.merge(df1, df2, on='id', how='inner')   #inner joint


df3.rename(columns={'name_x':'table_name1','age_x':'age'},inplace=True)      #used for renameing the column name

display(df3)
print(" ")



df4 = pd.merge(df1, df2, on='id', how='left')   #left joint
display(df4)
print(" ")


df5 = pd.merge(df1, df2, on='id', how='right')   #right joint
display(df5)
print(" ")


df6 = pd.merge(df1, df2, on='id', how='outer')   #outer joint
display(df6)
print(" ")


df7 = pd.merge(df1, df2, how='cross')   #cross joint
display(df7)
print(" ")


df8 = pd.concat([df1,df2])               #concat dono table ko upar niche join kar deta hain
display(df8)
print(" ")


df9 = pd.concat([df1,df2],axis=1)         #dono table ko side by side join kar dega with every column mtlb id 2 baar aayega table mein bhi
display(df9)
print(" ")

   id table_name1  age name_y  age_y
0   3       Rahul   35  Rahul     35
1   4        Rhea   40   Rhea     40

   id name_x  age_x name_y  age_y
0   1   Raju     25    NaN    NaN
1   2   Rani     30    NaN    NaN
2   3  Rahul     35  Rahul   35.0
3   4   Rhea     40   Rhea   40.0

   id name_x  age_x name_y  age_y
0   3  Rahul   35.0  Rahul     35
1   4   Rhea   40.0   Rhea     40
2   5    NaN    NaN   Ravi     45
3   6    NaN    NaN  Reena     50

   id name_x  age_x name_y  age_y
0   1   Raju   25.0    NaN    NaN
1   2   Rani   30.0    NaN    NaN
2   3  Rahul   35.0  Rahul   35.0
3   4   Rhea   40.0   Rhea   40.0
4   5    NaN    NaN   Ravi   45.0
5   6    NaN    NaN  Reena   50.0

    id_x name_x  age_x  id_y name_y  age_y
0      1   Raju     25     3  Rahul     35
1      1   Raju     25     4   Rhea     40
2      1   Raju     25     5   Ravi     45
3      1   Raju     25     6  Reena     50
4      2   Rani     30     3  Rahul     35
5      2   Rani     30     4   Rhea     40
6      2   Rani     30     5   Ravi     45
7      2   Rani     30     6  Reena     50
8      3  Rahul     35     3  Rahul     35
9      3  Rahul     35     4   Rhea     40
10     3  Rahul     35     5   Ravi     45
11     3  Rahul     35     6  Reena     50
12     4   Rhea     40     3  Rahul     35
13     4   Rhea     40     4   Rhea     40
14     4   Rhea     40     5   Ravi     45
15     4   Rhea     40     6  Reena     50

   id   name  age
0   1   Raju   25
1   2   Rani   30
2   3  Rahul   35
3   4   Rhea   40
0   3  Rahul   35
1   4   Rhea   40
2   5   Ravi   45
3   6  Reena   50

   id   name  age  id   name  age
0   1   Raju   25   3  Rahul   35
1   2   Rani   30   4   Rhea   40
2   3  Rahul   35   5   Ravi   45
3   4   Rhea   40   6  Reena   50

In [ ]:
df1 = pd.DataFrame({
    'id':[1,2,3,4,1,1,3,4],
    'name':['Raju','Rani','Rahul','Rhea','Raju','Raju','Rahul','Rhea'],
    'age':[25,30,35,40,25,25,35,40]
})

df2 = pd.DataFrame({
    'id':[3,4,5,6],
    'name':['Rahul','Rhea','Ravi','Reena'],
    'age':[35,40,45,50]

})


df3 = pd.merge(df1, df2, on='id', how='inner')

#drop_duplicates duplicate value ko remove kar deta hain or agar uske parameter mein subset mein id likhenge toh woh sirf id jo unique hogi usko print karega agar koi parameter nahi hoga toh
#jo jo equal hain puri row mein unko element karega or 1 hi baar likhega


#drop_duplicates() duplicate rows ko remove karne ke liye use hota hai. Hum decide kar sakte hain kis
#column ke basis par duplicate check karna hai aur kaunsi duplicate row rakhni hai.

df3.drop_duplicates(subset = ['id'], keep='first', inplace = True)
display(df3)

   id name_x  age_x name_y  age_y
0   3  Rahul     35  Rahul     35
1   4   Rhea     40   Rhea     40

In [ ]:
#pivot table concept

#Pivot table ek table ki values ko apne se place karta hain mtlb agar column mein hume not placed placed likhna hain or uske ander study hours ka mean nikalna hain toh uske liye use hota hain



#Pivot Table: Data ko summarize karne ke liye use hoti hai.
#Ek column ki values ko rows ya columns mein arrange karke kisi
#numeric value ka summary (mean, sum, count, etc.) nikalti hai.

In [ ]:
import pandas as pd

df = pd.read_csv('student_data.csv')

In [ ]:
df.pivot_table(columns = 'placement_status', index = 'sleep_hours', values = 'exam_score', aggfunc = 'mean')

placement_status  Not Placed     Placed
sleep_hours
4                  59.424160  90.483113
5                  58.306079  91.085519
6                  60.971968  91.819595
7                  59.650121  92.279986
8                  60.091122  93.062072
9                  61.181129  92.987227

In [ ]:
df.pivot_table(columns = 'study_hours', index = 'sleep_hours', values = 'assignments_completed', aggfunc = 'mean')

study_hours,1,2,3,4,5,6,7,8,9,10,11
sleep_hours,,,,,,,,,,,
4,9.980392,10.283784,10.166667,9.529801,10.187050,10.530612,9.836158,10.486111,9.950000,9.114458,9.662420
5,10.231707,9.837838,10.051948,9.706667,9.679487,10.604651,11.151515,10.118519,10.616279,9.886228,9.863946
6,10.566265,10.417808,10.229299,9.694805,10.066667,10.131737,9.934307,10.601399,9.868966,9.375000,9.291045
7,11.026846,9.166667,9.440252,10.007143,9.888889,9.606250,10.750000,8.380368,11.130719,10.506024,9.741007
8,9.303448,8.741935,9.807692,10.204545,9.843373,10.105960,10.057325,9.967742,10.633987,10.060000,10.220000
9,10.245283,9.646667,9.968944,9.582822,10.308725,9.744681,10.355828,9.926667,10.085714,9.185185,10.141844